language: node_js
node_js:
  - "6"
  - "7"

language: ruby
rvm:
  - 2.4

install:
  - npm install
  - bundle install

script:
  - npm run lint
  - npm run test
  - rake acceptance_tests

after_success:
  - npm run ci-report-coverage
